version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: messagedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - producer1
      - producer2
      - producer3

  producer1:
    build:
      context: ./producer
      dockerfile: Dockerfile
    environment:
      - INSTANCE_ID=producer-1
    depends_on:
      - rabbitmq

  producer2:
    build:
      context: ./producer
      dockerfile: Dockerfile
    environment:
      - INSTANCE_ID=producer-2
    depends_on:
      - rabbitmq

  producer3:
    build:
      context: ./producer
      dockerfile: Dockerfile
    environment:
      - INSTANCE_ID=producer-3
    depends_on:
      - rabbitmq

  consumer1:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    environment:
      - INSTANCE_ID=consumer-1
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq

  consumer2:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    environment:
      - INSTANCE_ID=consumer-2
    ports:
      - "8082:8081"
    depends_on:
      - rabbitmq

  consumer3:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    environment:
      - INSTANCE_ID=consumer-3
    ports:
      - "8083:8081"
    depends_on:
      - rabbitmq